### ISSUE TITLE
Question about JavaScript vs Typescript

### ISSUE THREAD

**Issue by coffeeneed** [PeterStaev/nativescript-purchase#82] opened 2019-08-20 07:13 UTC
Hi! When I started my Nativescript project I chose JavaScript as coding language, not TypeScript. Will I be able to use this plugin using JavaScript?

**Comment by PeterStaev** [comment] 2019-08-20 18:44
Any nativescript plugin is compatible with Core TS and Core JS flavors of NS. So yes, you will be able to use it. You just need to adapt the demos/examples to how you import things in JS.

**Comment by PeterStaev** [comment] 2019-09-08 21:19
No further response so closing this one for now. In case you still have problems, please provide more details.

**Closed as completed by PeterStaev** 2019-09-08 21:19 UTC
Labels: question

**Comment by MariSpr** [comment] 2019-10-30 11:38
Hey, sorry for reopening the thread.i recently published an js app using vanilla js (after changing code) and it works fine in Android, however, my app was rejected by the app store as it crashed on launch (even though I could not reproduce any crashes on real devices or emulators.

Anyway, I removed the plug-in and republished and the app was approved, so I wonder if there are any known issues with iOS?

I will try again but wonder if have to keep the references.ts or change them to js?

Thanks in advance! Mariana

**Comment by PeterStaev** [comment] 2019-10-30 11:51
Hey @MariSpr , as far as I know there are no issues with iOS. 

There is no need to keep the TS files in the release bundle.
